feat(treeset): add treeset api
harttle/contest.js pull request #15
Opened 2022-01-14 06:52 UTC by 981377660LMT

- 为 Treeset 和 TreeMultiSet 增加了shift、pop、first、last 方法
- 修复了 TreeMultiSet 的 delete 方法删除不存在元素时的bug
- 增加了eslint 配置

2022-01-14 08:03 UTC, harttle requested changes

2022-01-14 08:03 UTC, harttle commented on tsconfig.json
> +    "target": "ESNext" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
target 只用来控制生成的 JS，它用于 npm，保持在 es6 更兼容。至于需要 human readable 的代码，都在仓库源码里，通过 README 链接。

2022-01-14 08:03 UTC, harttle commented on treeset.ts
> +  }
Asesome!

2022-01-14 11:08 UTC, upupming commented on .eslintrc.js
> +    'yield-star-spacing': 0
build出来的代码还是要禁用eslint比较好，可以eslintignore配一下

2022-01-14 11:08 UTC, upupming commented on .prettierrc
> +}
standardjs好像已经包含了引号和逗号的规范，prettier是多余的。如果不用standard，是可以同时使用prettier的eslint插件的(避免规则冲突)。

2022-01-14 11:58 UTC, 981377660LMT commented on .eslintrc.js
> +    'yield-star-spacing': 0
好的 我这里还是按照原来的eslint配置来

2022-01-14 12:00 UTC, 981377660LMT commented on tsconfig.json
> +    "target": "ESNext" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
![image](https://user-images.githubusercontent.com/45849137/149512073-4351e82f-7bdb-4ce3-b076-cdb2d6c49ba9.png)
target 为 es6时，ts 检查器 提示 bigInt 不可用；这里我还是先改回 es6

2022-01-14 14:41 UTC, harttle commented on tsconfig.json
> +    "target": "ESNext" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
原来如此，那搞成 "es2020" 吧！

2022-01-15 06:20 UTC, 981377660LMT commented
多加了一个 Treap 数据结构 可以当一个 sortedList 用 
力扣 [2102. 序列顺序查询]( https://leetcode-cn.com/problems/sequentially-ordinal-rank-tracker/) 的测试效果
![image](https://user-images.githubusercontent.com/45849137/149611522-5fadd97e-5233-4bbf-849d-88e32f64d5e1.png)

2022-01-18 09:09 UTC, harttle approved these changes

2022-05-15 06:28 UTC, merged